openmrs/openmrs-owa-labworkflow

- app/js/components/LabOrdersList.jsx
- app/js/components/shared/BreadCrumb/BreadCrumb.jsx
- app/js/openmrs-owa-labworkflow.jsx
- app/js/routes.jsx
- app/js/translations/en.json
- app/js/translations/fr.json
- package-lock.json
- package.json
- tests/components/LabOrderList/LabOrdersList.spec.jsx
- tests/components/LabOrderList/__snapshots__/LabOrdersList.spec.jsx.snap
- tests/components/breadcrumb/Breadcrumb.spec.js
- tests/components/breadcrumb/__snapshots__/Breadcrumb.spec.js.snap
> UHM-3471: implement localization

- app/js/components/LabOrdersList.jsx
- app/js/translations/en.json
- app/js/translations/fr.json
> UHM:3478: Implement UI tweaks

- app/css/lab-orders-list.scss
- app/css/openmrs-owa-labworkflow.scss
- app/js/components/LabOrdersList.jsx
- package-lock.json
> UHM-3477: fix filtering bug

- app/css/lab-orders-list.scss
- app/css/openmrs-owa-labworkflow.scss
- app/js/components/LabOrdersList.jsx
- app/js/components/LabOrdersListFilters.jsx
> UHM-3478: implement styling feedback

- app/js/components/LabResultEntry.jsx
> UHM-3487: Modify Obs component to render ButtonGroup or Dropdown

- app/js/actions/labOrdersAction.js
- app/js/components/LabOrdersList.jsx
- app/js/middlewares/errorMiddleware.js
- app/js/mockData/mockOrders.json
- app/js/reducers/labOrdersReducer.js
- app/js/redux-store.jsx
- app/js/routes.jsx
- app/js/sagas/labOrdersSaga.js
- app/js/translations/en.json
- app/js/translations/fr.json
- tests/middlewares/errorMiddleWare.js
- tests/reducers/labOrdersReducer.spec.js
- tests/sagas/labOrdersSaga.spec.js
This PR also fixes an error with orders fetching in production environment.
> UHM-3504: Changed Lab workflow app title

- app/css/lab-result-entry.scss
- app/js/components/LabResultEntry.jsx
- app/js/utils/helpers.js
> UHM-3478: Move submit and cancel button to outside the fieldset

- tests/components/LabOrderList/__snapshots__/LabOrdersList.spec.jsx.snap
- tests/components/LabOrdersListFilters/__snapshots__/LabOrdersListFilters.spec.jsx.snap
- tests/components/LabResultEntry/LabResultEntry.spec.jsx
- tests/components/LabResultEntry/__snapshots__/LabResultEntry.spec.jsx.snap
> Fix failing test

- app/css/lab-result-entry.scss
- app/js/actions/labOrdersAction.js
This PR also fixes some alignment issues
> UHM-3573: Fetch only lab orders

- app/css/lab-orders-trends-page.scss
- app/js/actions/actionTypes.js
- app/js/actions/labOrdersAction.js
- app/js/components/LabOrdersList.jsx
- app/js/components/LabResultsList.jsx
- app/js/components/LabTrendsPage.jsx
- app/js/components/RangeCell.jsx
- app/js/reducers/index.js
- app/js/reducers/initialState.js
- app/js/reducers/labOrderTrendsReducer.js
- app/js/reducers/labTestResultsReducer.js
- app/js/routes.jsx
- app/js/utils/helpers.js
- package-lock.json
- tests/actions/labOrdersAction.spec.js
- tests/components/LabOrderList/__snapshots__/LabOrdersList.spec.jsx.snap
- tests/components/LabOrdersListFilters/__snapshots__/LabOrdersListFilters.spec.jsx.snap
- tests/components/LabResultEntry/__snapshots__/LabResultEntry.spec.jsx.snap
- tests/components/LabTrendsPage/LabTrendsPage.spec.jsx
- tests/reducers/labOrderTrendsReducer.spec.js
Access this page by clicking on a single test from the `LabResultList` page
> UHM:3494: Add lab trends page

- app/js/components/LabOrdersList.jsx
- app/js/components/LabResultsList.jsx
Follow up to the previous PR,
modified logic for ordering lab results
> UHM-3337 : Lab Results Page

- app/css/lab-orders-list.scss
- app/js/components/LabOrdersList.jsx
- app/js/components/LabOrdersListFilters.jsx
- app/js/components/LabsStatusDisplay.jsx
- app/js/utils/helpers.js
- tests/components/LabOrderList/__snapshots__/LabOrdersList.spec.jsx.snap
- tests/components/LabOrdersListFilters/__snapshots__/LabOrdersListFilters.spec.jsx.snap
> UHM-3609: Add test status to labOrderList Page 

- app/css/lab-result-entry.scss
- app/js/components/LabResultEntry.jsx
> UHM-3545: Fix alignment issues

- app/js/components/LabOrdersList.jsx
- app/js/components/LabOrdersListFilters.jsx
- app/js/components/LabResultEntry.jsx
- tests/components/LabOrderList/__snapshots__/LabOrdersList.spec.jsx.snap
- tests/components/LabOrdersListFilters/__snapshots__/LabOrdersListFilters.spec.jsx.snap
- tests/components/LabResultEntry/__snapshots__/LabResultEntry.spec.jsx.snap
Link to ticket description: https://tickets.pih-emr.org/secure/RapidBoard.jspa?rapidView=68&view=detail&selectedIssue=UHM-3703
> UHM-3703: Fix Datepicker

- app/js/utils/globalProperty.js
Creating global property for ticket UHM-4138
> Add orders directly from Labs page

- app/js/openmrs-owa-labworkflow.jsx
- package-lock.json
- package.json
- webpack.config.js
(Experimental), but this makes labworkflow OWA function as a microfrontend.
> Switching over to a single-spa application

- package-lock.json
- package.json
- webpack.config.js
Run `npm run analyze` to see this:
> Adding npm run analyze script to debug bundle size.

- app/js/components/LabResultEntry.jsx
This is a PSA about code review
> Fix typo 'heigth'

- app/js/components/LabResultsList.jsx
- app/js/sagas/patientSaga.js
- app/js/utils/helpers.js
- tests/components/ConceptDisplay/__snapshots__/ConceptDisplay.spec.jsx.snap
- tests/components/LabOrderList/__snapshots__/LabOrdersList.spec.jsx.snap
- tests/components/LabOrdersListFilters/__snapshots__/LabOrdersListFilters.spec.jsx.snap
- tests/components/LabResultEntry/__snapshots__/LabResultEntry.spec.jsx.snap
- tests/components/LabTrendsPage/__snapshots__/LabTrendsPage.spec.jsx.snap
- tests/components/breadcrumb/__snapshots__/Breadcrumb.spec.jsx.snap
- tests/utils/helpers.spec.js
https://pihemr.atlassian.net/browse/UHM-4460
> UHM-4460 Use shortname for lab results

- app/js/components/LabResultsList.jsx
- tests/components/LabOrderList/__snapshots__/LabOrdersList.spec.jsx.snap
- tests/components/breadcrumb/__snapshots__/Breadcrumb.spec.jsx.snap
https://pihemr.atlassian.net/browse/UHM-4537
> UHM-4537 Lab Results not showing on patient results view

- app/css/lab-orders-list.scss
- app/js/components/LabOrdersList.jsx
- app/js/translations/en.json
https://pihemr.atlassian.net/browse/UHM-4535
> UHM-4535 pt 1: Add lab id column to lab orders list page

- app/css/lab-result-entry.scss
- app/js/components/LabResultEntry.jsx
UHM-4562 Calendar cut off in lab result entry page
https://pihemr.atlassian.net/browse/UHM-4562
UHM-4516 Overlapping units and ranges on lab results page
https://pihemr.atlassian.net/browse/UHM-4516
> UHM-4562 calendar and UHM-4516 overlap

- app/css/lab-results-view.scss
- app/js/components/LabResultsList.jsx
- tests/components/LabOrderList/__snapshots__/LabOrdersList.spec.jsx.snap
- tests/components/LabOrdersListFilters/__snapshots__/LabOrdersListFilters.spec.jsx.snap
- tests/components/LabResultEntry/__snapshots__/LabResultEntry.spec.jsx.snap
https://pihemr.atlassian.net/browse/UHM-4566
I wasn't able to get my screen to emulate what Dave was seeing at either the device size he's using or the actual device size. Probably something about pixel ratio. Anyway, here's some screenshots:
Laptop:
Compressed to right before gender and age wrap down in the patient banner:
As narrow as it gets before the table gets a scrollbar:
With some collections open:
> UHM-4566 View Labs page on tablet

- app/js/components/LabResultEntry.jsx
https://pihemr.atlassian.net/browse/UHM-4604
Fixes bug introduced in https://github.com/openmrs/openmrs-owa-labworkflow/commit/6451a7d615ee4d4eb7cd1c536f8d2d5e188fced6#r39590822
> UHM-4604 Cannot enter reason not performed

- app/js/actions/labOrdersAction.js
- app/js/components/LabOrdersList.jsx
- app/js/utils/helpers.js
As I was debugging this problem I was getting a NPE exception(undefined) because the patient.display field was empty, so I added an extra check.
> UHM-5053, fulfiller status takes precedence

- app/js/actions/labOrdersAction.js
- app/js/components/LabOrdersList.jsx
- app/js/utils/helpers.js
Thanks @mogoodrich ! That makes sense regarding of using person.display. I also adjust the date filter. Thanks!
> UHM-5053, use person display and adjust date range filter

- app/js/actions/labOrdersAction.js
- app/js/components/LabOrdersList.jsx
- app/js/components/LabOrdersListFilters.jsx
- app/js/utils/helpers.js
@mogoodrich , per your suggestions on this ticket, I have removed the canceled/expired filter. Thanks!
> UHM-5053, remove canceled/expired status filter

- app/js/components/LabResultsList.jsx
https://pihemr.atlassian.net/browse/UHM-6224
> UHM-6224 Fix: Should be able to print lab list for a specific patient

- .eslintrc
- app/css/lab-results-view.scss
- app/js/components/ConceptDisplay.jsx
- app/js/components/LabResultsList.jsx
Resolves Debbie's feedback on https://pihemr.atlassian.net/browse/UHM-6224 , except for the note about text wrapping.
[Lab 2012-04-13 2022-04-13.pdf](https://github.com/openmrs/openmrs-owa-labworkflow/files/8484864/Lab.2012-04-13.2022-04-13.pdf)
> Patient lab results should all print, with a patient banner and some margin

- app/js/components/LabResultsList.jsx
https://pihemr.atlassian.net/browse/UHM-6224
[Lab 2012-04-19 2022-04-19.pdf](https://github.com/openmrs/openmrs-owa-labworkflow/files/8517793/Lab.2012-04-19.2022-04-19.pdf)
> UHM-6224, part 3: Separate tables on separate pages

- app/css/lab-results-view.scss
- app/js/components/LabResultsList.jsx
> UHM-6224, part 4: Better page breaking; loading spinner

- app/js/components/LabResultsList/LabResultsTable.jsx
https://pihemr.atlassian.net/browse/UHM-6511
> UHM-6511 Paging broken on View Lab Results (HUM production)

- app/js/components/LabResultsList/LabResultsTable.jsx
> Fix lint error

- app/js/components/LabResultsList/LabResultsTable.jsx
https://pihemr.atlassian.net/browse/UHM-6527
> UHM-6527 Lab results page Test Type filter leaves results on separate pages

- app/js/components/LabResultsList/LabResultsList.jsx
- app/js/components/LabResultsList/LabResultsTable.jsx
https://pihemr.atlassian.net/browse/UHM-6512
> UHM-6512 History view not appearing on View Lab Results page

- app/js/components/LabResultsList/LabResultsList.jsx
- app/js/components/LabResultsList/LabResultsTable.jsx
- app/js/sagas/conceptSaga.js
Here is the change to display the SHORT NAME of the concept that represent the lab category.
> UHM-6638, display lab categories using concept SHORT NAMEs

- app/js/components/LabResultsList/LabResultsTable.jsx
- app/js/sagas/conceptSaga.js
Add support for filtering by tests nested within panels
> UHM-6643: Lab OWA Assessments and Tweaks

- app/js/components/LabResultsList/LabResultsList.jsx
- app/js/components/shared/BreadCrumb/BreadCrumb.jsx
- app/js/utils/helpers.js
@mseaton , @mogoodrich : I had to refactor again the returnUrl to handle the Back button navigation.
> UHM-8309: refactor url for the Back button
